teleop:
  go:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel 
    axis_mappings:
      -
        axis: 4
        target: linear.x
        scale: 1.0
      -
        axis: 3
        target: angular.z
        scale: 1.0

  